### ISSUE TITLE
How to use it from web browser?

### ISSUE THREAD

**Issue by qiangweihewu** [rodukov/TelegramCloud#1]
Hi there! 
Thanks for your wonderful work! Following your instructions, I successfully built the API and could use it on terminal. However, I wonder if there are more specific instructions for deploying the frontend so that it can be visited from web browser.
Look forward to your reply, thanks!

**Comment by res138** [comment]
`vue-cli-service serve` - to run in web
`vue-cli-service build` - to build deploy
Also you can edit your `package.json`
```
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
```
