### ISSUE TITLE
[Question] Slow upload speed

### ISSUE THREAD

**Issue by shirooo39** [rodukov/TelegramCloud#2]
Is it normal for the upload speed to be extremely slow?

I tried to upload a few files from a 2Gbps Google VM but it takes forever to complete just a single upload.

**Comment by res138** [comment]
_Looking at the size of the file. Small files transfer easily. However, huge ones take time._

**Comment by shirooo39** [comment]
> _Looking at the size of the file. Small files transfer easily. However, huge ones take time._

I also tried this project called teledrive that acts kind of an indexer.
even uploading from teledrive is also extremely slow.

so I suspected that telegram did intentionally limit upload speed to their servers
